# Supabase configuration for Instructly platform
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://instructly.com", "https://instructly-staging.vercel.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_password_change = true
enable_confirmations = true

[auth.external]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation_enabled = true

[analytics]
enabled = false

[functions]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327